name: Linux/CMake

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug,Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Ninja
      run: |
        sudo apt-get update
        sudo apt-get -y install -y ninja-build
        
    - name: Install Catch2
      run: |
        git clone https://github.com/catchorg/Catch2.git
        cd Catch2
        git checkout v2.x
        cmake -Bbuild -H. -DBUILD_TESTING=OFF
        sudo cmake --build build/ --target install
        
    - name: Display tools versions
      run: |
        ninja --version
        cmake --version
        gcc --version
        
    - name: Configure CMake
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      # Build your program with the given configuration
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    # - name: Testing Algebra Component
    #   working-directory: ${{github.workspace}}/build
    #   run: tests/number/algebra_tests
      
    #  - name: Testing Calculus Component
    #   working-directory: ${{github.workspace}}/build
    #   run: tests/number/calculus_tests
      
    #  - name: Testing Discrete Component
    #   working-directory: ${{github.workspace}}/build
    #  run: tests/number/discrete_tests
      
    #  - name: Testing Geometry Component
    #   working-directory: ${{github.workspace}}/build
    #   run: tests/number/geometry_tests
      
    - name: Testing Number Component
      working-directory: ${{github.workspace}}/build
      run: tests/number/number_tests
      
    # - name: Testing Statistics Component
    #   working-directory: ${{github.workspace}}/build
    #   run: tests/number/statistics_tests
      
