name: Linux build basic

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ubuntu-latest
    strategy: 
      fail-fast: false
      matrix:
        cxx:
            - g++10
            - clang++10
        build_type: [Debug,Release]
        std: [11]
        
    steps:
      - uses: actions/checkout@v3
      - name: Print env
        run: |
          echo github.event.action: ${{ github.event.action }}
          echo github.event_name: ${{ github.event_name }}
      - name: Install dependencies on ubuntu
        if: startsWith(matrix.config.name, 'Ubuntu_Latest_GCC')
        run: |
          sudo apt-get update
          sudo apt-get install ninja-build cmake
          ninja --version
          cmake --version
          gcc --version
          
      - name: Configure
        shell: bash
        run: |
          mkdir build
          mkdir instdir
          cmake \
            -Bbuild -H$GITHUB_WORKSPACE \
            -DCMAKE_CXX_STANDARDS=${{matrix.std}} \
            -DCMAKE_BUILD_TYPE=${{matrix.config.build_type}} \
            -G Ninja
      
      - name: Build tests + lib
        working-directory: ${{runner.workspace}}/build
        run: ninja

      - name: Run tests
        env:
          CTEST_OUTPUT_ON_FAILURE: 1
        working-directory: ${{runner.workspace}}/build
        # Hardcode 2 cores we know are there
        run: ctest -C ${{matrix.build_type}}
